name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'  # Запускать при пуше тегов, начинающихся с 'v'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine toml
      
      - name: Update version in pyproject.toml
        run: |
          # Получаем версию из тега (убираем 'v' из начала)
          VERSION=${GITHUB_REF#refs/tags/v}
          # Обновляем версию в pyproject.toml
          python -c "
          import toml
          config = toml.load('pyproject.toml')
          config['project']['version'] = '${VERSION}'
          with open('pyproject.toml', 'w') as f:
              toml.dump(config, f)
          "
          
      - name: Build package
        run: python -m build
      
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/* 