name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'  # Запускать при пуше тегов, начинающихся с 'v'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine toml
      
      - name: Update version in pyproject.toml and __init__.py
        run: |
          # Получаем версию из тега (убираем 'v' из начала)
          VERSION=${GITHUB_REF#refs/tags/v}
          
          # Обновляем версию в pyproject.toml
          python -c "
          import toml
          config = toml.load('pyproject.toml')
          config['project']['version'] = '${VERSION}'
          with open('pyproject.toml', 'w') as f:
              toml.dump(config, f)
          "
          
          # Обновляем версию в __init__.py
          python -c "
          import re
          with open('gosms_ru_client/__init__.py', 'r') as f:
              content = f.read()
          content = re.sub(r'__version__ = \"[^\"]*\"', '__version__ = \"${VERSION}\"', content)
          with open('gosms_ru_client/__init__.py', 'w') as f:
              f.write(content)
          "
          
      - name: Build package
        run: python -m build
      
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/* 