name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'  # Запускать при пуше тегов, начинающихся с 'v'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine toml requests
      
      - name: Check if version exists
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          # Проверяем существование версии через PyPI API
          if curl -s "https://pypi.org/pypi/gosms-ru-client/${VERSION}/json" | grep -q "version"; then
            echo "Version ${VERSION} already exists on PyPI. Please use a different version."
            exit 1
          fi
      
      - name: Update version in pyproject.toml and __init__.py
        run: |
          # Получаем версию из тега (убираем 'v' из начала)
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "Updating to version: ${VERSION}"
          
          # Обновляем версию в pyproject.toml
          python -c "import toml, os; version = os.environ['VERSION']; config = toml.load('pyproject.toml'); config['project']['version'] = version; toml.dump(config, open('pyproject.toml', 'w')); print(f'Updated pyproject.toml to version {version}')"
          
          # Обновляем версию в __init__.py
          python -c "import re, os; version = os.environ['VERSION']; content = open('gosms_ru_client/__init__.py', 'r').read(); content = re.sub(r'__version__ = \"[^\"]*\"', f'__version__ = \"{version}\"', content); open('gosms_ru_client/__init__.py', 'w').write(content); print(f'Updated __init__.py to version {version}')"
      
      - name: Build package
        run: python -m build
      
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
          VERSION: ${{ github.ref_name }}
        run: twine upload dist/* 